### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by JonathanFrias** [searls/jasmine-rails#196]
I followed the README exactly, but I have this error without much detail
```
$ bundle exec rake spec:javascript --trace RAILS_ENV=test
** Invoke spec:javascript (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute spec:javascript
Running `"/Users/jonathan/.phantomjs/2.1.1/darwin/bin/phantomjs" "" "path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file://path/to/my_app/tmp/jasmine/runner.html?spec="`
Running: file://path/to/my_app/tmp/jasmine/runner.html?spec=
rake aborted!
Error executing command: "/Users/jonathan/.phantomjs/2.1.1/darwin/bin/phantomjs" "" "path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file://path/to/my_app/tmp/jasmine/runner.html?spec="
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/runner.rb:73:in `run_cmd'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/runner.rb:23:in `block in run'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/runner.rb:50:in `override_rails_config'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/jasmine_rails/runner.rb:9:in `run'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/jasmine-rails-0.12.5/lib/tasks/jasmine-rails_tasks.rake:9:in `block (2 levels) in <top (required)>'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
path/to/my_app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
path/to/my_app/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
path/to/my_app/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<top (required)>'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/jonathan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/Users/jonathan/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
/Users/jonathan/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'
Tasks: TOP => spec:javascript
```
I also have `spec/javascripts/test_spec.js`
```javascript
describe("stuff", function() {
  it("runs", function() {
    expect(1+1).toBe(2);
  });
});
```

The jasmine.yml is the generated one

**Comment by searls** [comment]
Did you resolve this issue?

**Comment by JonathanFrias** [comment]
Yeah I did, it just sorta worked after I reinstalled the gems. I wish i had a better analysis. 

It would be nice to get better error messages though. (My guess is those messages are bleeding through from phantomjs)
