### ISSUE TITLE
Error executing command

### ISSUE THREAD

**Issue by taleschaves** [searls/jasmine-rails#209]
Hi,

I recently updated jasmine-rails to 0.14.1 and phantomjs to 2.1.1. Although, when I run rake spec:javascript  I get this error:

± tc |master ✗| → rake spec:javascript --trace
** Invoke spec:javascript (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute spec:javascript
Running `"/home/gandalf/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs" "" "/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///home/gandalf/workspace/gemini/tmp/jasmine/runner.html?spec="`
Running: file:///home/gandalf/workspace/gemini/tmp/jasmine/runner.html?spec=
rake aborted!
Error executing command: "/home/gandalf/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs" "" "/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///home/gandalf/workspace/gemini/tmp/jasmine/runner.html?spec="
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/runner.rb:77:in `run_cmd'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/runner.rb:23:in `block in run'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/runner.rb:48:in `override_rails_config'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/jasmine_rails/runner.rb:9:in `run'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/gems/jasmine-rails-0.14.1/lib/tasks/jasmine-rails_tasks.rake:9:in `block (2 levels) in <top (required)>'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/bin/ruby_executable_hooks:15:in `eval'
/home/gandalf/.rvm/gems/ruby-2.3.1@gemini/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec:javascript
(See full trace by running task with --trace)

Is there any way to get more debug information through jasmine-rails?

**Comment by searls** [comment]
Personally, I would open up the gem and drop pry or a debugger to figure out what might be going on. My familiarity with the code is about as good at yours at this point, since it's been so long since I've worked on/with it

**Comment by jamescgibson** [comment]
@taleschaves Did you end up making any headway on this? I have the same issue, though not after an upgade; I can run specs fine in the browser but not from the command line and have essentially the same error.
